[package]
name = "xpcom-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.138"
serde_derive = "1.0.138"
serde_json = "1.0.82"
serde_yaml = "0.8.24"
