[package]
name = "u160"
version = "0.2.0"
edition = "2021"
description = "Unsigned Integer 160 bits"
license = "Apache-2.0"
repository = "https://github.com/natfoam/lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
