[package]
name = "fixed-array"
version = "0.4.1"
description = "Fixed-size array"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
