[package]
name = "bit-list"
version = "0.1.0"
authors = ["natfoam"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uints = "0.2.0"
list-fn = "0.3.0"