[package]
name = "bit-list"
version = "0.2.0"
authors = ["natfoam"]
edition = "2018"
description = "A lazy list of bits"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uints = { path = "../uints", version = "0.2.0" }
list-fn = { path = "../list-fn", version = "0.4.0" }